// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cixjxbtjbnqnhxtzpoey.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNpeGp4YnRqYm5xbmh4dHpwb2V5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5ODU5MTIsImV4cCI6MjA3MjU2MTkxMn0.YNCkdGL8b1oG9YindWInj8noIkEEpz2EXZQjTwoQUO8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});